name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: ">=3.0.0 <4.0.0"

isar_version: &isar_version 3.1.8
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.5.2
  synchronized: ^3.3.1
  universal_io: ^2.2.2
  graphql_flutter: ^5.1.2
  ntp: ^2.0.0
  universal_platform: ^1.1.0
  amazon_cognito_identity_dart_2: ^3.8.1
  source_gen: ^1.5.0
  pool: ^1.5.1
  random_string: ^2.3.1
  queue: ^3.4.0
  mime_type: ^1.0.1
  singleton: ^0.0.3-nullsafety
  tuple: ^2.0.2
  recase: ^4.1.0
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  sembast: ^3.8.4
  sembast_web: ^2.4.1

  robust_http:
    git:
      url: https://github.com/bookbot-kids/robust_http.git

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  equatable: ^2.0.7
