name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  path_provider: ^1.6.11
  uuid: ^2.0.4
  sembast: ^2.4.7+4
  jaguar_jwt: ^2.1.6
  shared_preferences: ^0.5.7+3
  synchronized: ^2.2.0+1
  universal_io: ^1.0.1
  sembast_web: ^1.2.0
  graphql_flutter: 3.1.0-beta.4
  basic_utils: ^2.5.4
  ntp: ^1.0.7
  universal_platform: ^0.1.3
  amazon_cognito_identity_dart_2: ^0.1.15
  source_gen: ^0.9.6

  robust_http:
    git:
      url: git://github.com/bookbot-kids/robust-http.git
      ref: 0.0.4


dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

