name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.1
  uuid: ^3.0.2
  sembast: ^3.0.0+4
  jaguar_jwt: ^2.1.6
  shared_preferences: ^2.0.5
  synchronized: ^3.0.0
  universal_io: ^2.0.1
  sembast_web: ^2.0.0+2
  graphql_flutter: ^4.0.1
  ntp: ^1.0.8
  universal_platform: ^0.1.3
  amazon_cognito_identity_dart_2: ^1.0.0-nullsafety.3
  source_gen: ^0.9.10+4
  pool: ^1.5.0
  random_string: ^2.1.0
  connectivity: ^3.0.3

  robust_http:
    git:
      url: git://github.com/bookbot-kids/robust-http.git

dependency_overrides:
  universal_io: ^2.0.1
  crypto: ^3.0.0
  http_parser: ^4.0.0
  path_provider: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

