name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.0
  path_provider: ^1.5.1
  better_uuid: ^0.1.2
  intl: ^0.16.0
  sembast: ^2.1.2+3
  dio: ^3.0.5
  connectivity: ^0.4.5+3
  jaguar_jwt: ^2.1.6
  shared_preferences: ^0.5.6+2
  synchronized: ^2.2.0
  sembast_web: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter

