name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.2
  uuid: ^3.0.4
  sembast: ^3.1.0+2
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.0.6
  synchronized: ^3.0.0
  universal_io: ^2.0.4
  sembast_web: ^2.0.0+2
  graphql_flutter: ^4.0.1
  ntp: ^2.0.0
  universal_platform: ^1.0.0+1
  amazon_cognito_identity_dart_2: ^1.0.3
  source_gen: ^1.0.2
  pool: ^1.5.0
  random_string: ^2.1.0
  connectivity: 3.0.3
  queue: ^3.1.0

  robust_http:
    git:
      url: git://github.com/bookbot-kids/robust-http.git

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

dependency_overrides:
  path_provider: ^2.0.2