name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  uuid: ^3.0.6
  sembast: ^3.2.0+1
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+2
  universal_io: ^2.0.4
  sembast_web: ^2.0.1+1
  graphql_flutter: ^5.1.1-beta.3
  ntp: ^2.0.0
  universal_platform: ^1.0.0+1
  amazon_cognito_identity_dart_2: ^3.0.0
  source_gen: ^1.2.2
  pool: ^1.5.1
  random_string: ^2.3.1
  queue: ^3.1.0+1
  mime_type: ^1.0.0
  singleton: ^0.0.3-nullsafety
  tuple: ^2.0.0

  robust_http:
    git:
      url: https://github.com/bookbot-kids/robust-http.git

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
dependency_overrides:
  path: ^1.8.2  