name: sync_db
description: A syncronising database that automatically gets and saves data to a server.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  path_provider: ^1.6.11
  uuid: ^2.0.4
  intl: ^0.16.1
  sembast: ^2.4.7+3
  dio: ^3.0.9
  connectivity: 0.4.8+2
  jaguar_jwt: ^2.1.6
  shared_preferences: ^0.5.7+3
  synchronized: ^2.2.0+1
  universal_io: ^1.0.1
  sembast_web: ^1.1.0+1
  pool: ^1.4.0
  graphql_flutter: 3.1.0-beta.4
  basic_utils: ^2.5.4
  ntp: 1.0.7
  universal_platform: ^0.1.3
  logger: 0.9.1


dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter

