name: sync_db
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Adrian DeWitts <adrian.dewitts@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
 #path: ^1.6.0
  flutter:
    sdk: flutter
  intl: ^0.16.0
  sembast: ^2.1.0+1
  dio: ^3.0.5
  connectivity: ^0.4.5+3

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter